### ISSUE TITLE
module initialization error: type object 'ShopifyResource' has no attribute '_url'

### ISSUE THREAD

**Issue by bputt** [Shopify/shopify_python_api#311]
The following code below is throwing the error: ```module initialization error: type object 'ShopifyResource' has no attribute '_url'```

This code was working in the 4.0.0 release, seems like the newest release has a regression?

```
def get_shopify_shop():
    shop_url = "https://{}:{}@{}.myshopify.com/admin".format(config.SHOPIFY_API_KEY, config.SHOPIFY_PASSWORD, config.SHOPIFY_SHOP)
    shopify.ShopifyResource.set_site(shop_url)
    return shopify.Shop.current()
```

**Comment by radovansurlak** [comment]
hey @bputt, I believe this is the culprit (taken from the Ruby version):
shop_url = "https://#{API_KEY}:#{PASSWORD}@#{SHOP_NAME}.myshopify.com"
ShopifyAPI::Base.site = shop_url
ShopifyAPI::Base.api_version = '<version_name>'

**Comment by muad-dweeb** [comment]
I'm very confused by this error. I never needed to generate a token or even directly use the Session class before. Am I required to now?

**Comment by radovansurlak** [comment]
> I'm very confused by this error. I never needed to generate a token or even directly use the Session class before. Am I required to now? This doesn't seem to be reflected in Step 2 of the Getting Started section of the README for private App setup.

I see, I have just locked it to version 4.0.0 for now. I believe it's not reflected in the README yet.
I think we just need a way to set the Shopify API version just as it is in the Ruby version.

**Comment by muad-dweeb** [comment]
Thanks, locking my version to 4.0.0 works for now as well.

**Comment by kayluhb** [comment]
I'm seeing the same issue with 

```
Python 3.7.2
```

I tried updating the site to include the api version, but to no avail
```
return "https://{}:{}@{}.myshopify.com/admin/api/2019-04".format(
        settings.SHOPIFY_APP_API_KEY, settings.SHOPIFY_APP_PASSWORD, settings.SHOPIFY_SHOP
)
```

I'm still getting this error.

```
~/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/shopify/base.py in connection(cls)
     43             local.format = cls.format
     44             local.version = cls.version
---> 45             local.url = cls.url
     46             if cls.site is None:
     47                 raise ValueError("No shopify session is active")
```

**Comment by tylerball** [comment]
Version 5.0.1 was just released with a fix for this, thanks for the reports everyone.

**Comment by JesseTG** [comment]
Has it made its way to PyPI yet?  I'm still only seeing 5.0.0.

**Comment by maurimontejo** [comment]
> Thanks, locking my version to 4.0.0 works for now as well.

How have you locked version 4.0.0?

**Comment by maurimontejo** [comment]
> Version 5.0.1 was just released with a fix for this, thanks for the reports everyone.

I'm still in the verison 5.0.0. I updated with pip install --upgrade ShopifyAPI, but it's still in version 5.0.0

**Comment by radovansurlak** [comment]
Hey, I did this by modifying my pipfile, or for you it could be changing
requirements.txt

**Comment by tylerball** [comment]
Sorry all! We had some issues with publishing the package, it's available now https://pypi.org/project/ShopifyAPI/5.0.1/
