### PR TITLE
fix missing class var on ShopifyResource

### LINKED ISSUE #311: module initialization error: type object 'ShopifyResource' has no attribute '_url'
The following code below is throwing the error: ```module initialization error: type object 'ShopifyResource' has no attribute '_url'```

This code was working in the 4.0.0 release, seems like the newest release has a regression?

```
def get_shopify_shop():
    shop_url = "https://{}:{}@{}.myshopify.com/admin".format(config.SHOPIFY_API_KEY, config.SHOPIFY_PASSWORD, config.SHOPIFY_SHOP)
    shopify.ShopifyResource.set_site(shop_url)
    return shopify.Shop.current()
```

### PR DESCRIPTION
**Pull request by tylerball**
Adds a missing class var to fix setting site with basic authentication. Closes #311 

@radovansurlak @bputt @muad-dweeb @kayluhb

### CODE REVIEW

**Comment by kayluhb** [comment]
Thanks @tylerball!

**Comment by monokal** [comment]
Following. This bug has hit my environment since 5.0.0 too.

**Comment by kayluhb** [comment]
Can this change get pushed to pypi?

**Comment by tylerball** [comment]
@kayluhb Apologies, we had some issues with publishing. It's available now https://pypi.org/project/ShopifyAPI/5.0.1/

**Comment by kayluhb** [comment]
Thanks again @tylerball !
